const CONFIG_VERSION = 3;

const PART_DEFAULTS = {
    icon: '',
    vehicle_durability_rate: 0.8,
    vehicle_damage_rate: 1.0,
    vehicle_damage_rate_destroyed: 0.1,
    functional_threshold: 0.3,
    share_durability: true,
    max_stack_size: 1,
    variants: {},
    element_markers: {},
};

const VARIANT_DEFAULTS = {
    model: '',
    textures: '',
    animations: null,
    tags: [],
    sub_parts: {},
};

const SUB_PART_DEFAULTS = {
    start_bone: '',
    end_bones: [],
    auto_end_bones: [],
    durability: 20.0,
    mass: 25.0,
    mass_center: 'mass_center',
    projected_area: [0, 0, 0],
    block_collision: 'true',
    collision_height: -1.0,
    climb_assist: false,
    hydro_priority: 0,
    hit_boxes: {},
    interact_boxes: {},
    connectors: {},
    subsystems: {},
    hydrodynamics: null,
};

const CONNECTOR_DEF_DEFAULTS = {
    type: 'Simple',
    direction: 'yp',
    integrity: 20.0,
    damage_reduction: 2.0,
    damage_multiplier: 1.5,
    damage_absorption: 0.2,
    collide_between: false,
    required_tags: [],
    accepted_tags: [],
    rejected_tags: [],
    joints: [],
};

const SUBSYSTEM_DEF_DEFAULTS = {
    type: 'machine_max:basic',
    basic_durability: 20.0,
    pass_damage: true,
    limit_damage: false,
    hidden: false,
    destroy_sound_event: null,
    activate_sound_event: null,
    deactivate_sound_event: null,
};

const HIT_BOX_DEFAULTS = {
    id: 'part',
    type: 'box',
    material: 'machine_max:default',
    thickness: 1.0,
    condition: 'true',
};

const MATERIAL_DEF_DEFAULTS = {
    friction: 0.5,
    restitution: 0.3,
    density: 1.0,
    armor_thickness: 1.0,
    armor_toughness: 0.0,
    hit_sound: null,
    break_sound: null,
    particle: null,
};

const PRESET_MATERIAL_DEFS = {
    'machine_max:structural_steel': {
        friction: [0.45, 0.45, 0.5],
        slip_adaptation: 0.55,
        rolling_friction: 0.22,
        spinning_friction: 0.0,
        restitution: 0.12,
        block_damage_factor: 1.1,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.7, condition: { type: 'always' } },
        ],
        penetration_modifiers: [
            { operation: 'multiply', value: 0.5, condition: { type: 'not', condition: { type: 'damage_tag', id: 'minecraft:bypasses_armor' } } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -6.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.06, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.06, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:rha': {
        friction: [0.35, 0.35, 0.5],
        slip_adaptation: 0.65,
        rolling_friction: 0.28,
        spinning_friction: 0.0,
        restitution: 0.07,
        block_damage_factor: 1.3,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.55, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -9.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.09, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.09, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:depleted_uranium_armor': {
        friction: [0.55, 0.55, 0.5],
        slip_adaptation: 0.3,
        rolling_friction: 0.01,
        spinning_friction: 0.4,
        restitution: 0.2,
        block_damage_factor: 0.7,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -4.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:5083_aluminum_alloy': {
        friction: [0.55, 0.55, 0.5],
        slip_adaptation: 0.60,
        rolling_friction: 0.02,
        spinning_friction: 0.50,
        restitution: 0.4,
        block_damage_factor: 0.7,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -4.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:7035_aluminum_alloy': {
        friction: [0.55, 0.55, 0.5],
        slip_adaptation: 0.66,
        rolling_friction: 0.01,
        spinning_friction: 0.43,
        restitution: 0.55,
        block_damage_factor: 0.7,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -4.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:glass': {
        friction: [0.65, 0.65, 0.5],
        slip_adaptation: 0.15,
        rolling_friction: 0.001,
        spinning_friction: 0.4,
        restitution: 0.6,
        block_damage_factor: 0.6,
        angle_effect: false,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
            { operation: 'add', value: -10.0, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -10.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.03, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.03, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.glass', range: 48 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.glass', range: 48 } },
    },
    'machine_max:hardwood': {
        friction: [0.65, 0.65, 0.5],
        slip_adaptation: 0.4,
        rolling_friction: 0.15,
        spinning_friction: 0.015,
        restitution: 0.2,
        block_damage_factor: 0.6,
        angle_effect: false,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
            { operation: 'add', value: -4.0, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -3.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.03, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.03, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.wood_hard', range: 48 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.wood_hard', range: 48 } },
    },
    'machine_max:softwood': {
        friction: [0.7, 0.7, 0.5],
        slip_adaptation: 0.35,
        rolling_friction: 0.12,
        spinning_friction: 0.02,
        restitution: 0.25,
        block_damage_factor: 0.4,
        angle_effect: false,
        impact_modifiers: [
            { operation: 'multiply', value: 0.9, condition: { type: 'always' } },
            { operation: 'add', value: -3.0, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -2.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.02, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.02, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.wood', range: 48 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.wood', range: 48 } },
    },
    'machine_max:normal_tire': {
        friction: [1.4, 1.5, 1.0],
        slip_adaptation: 0.4,
        slip_curve: { longitudinal: { peak_slip_ratio: 0.20, peak_scale: 1.4, kinetic_scale: 0.9 }, lateral: { peak_angle_deg: 12.0, peak_scale: 1.3, kinetic_scale: 0.8 } },
        rolling_friction: 0.01,
        spinning_friction: 0.8,
        restitution: 0.65,
        block_damage_factor: 0.05,
        impact_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
        ],
        damage_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'entity_type', id: 'minecraft:slime' } },
            { operation: 'multiply', value: 0.1, condition: { type: 'entity_type', id: 'minecraft:magma_cube' } },
        ],
    },
    'machine_max:off_road_tire': {
        friction: [1.2, 1.5, 1.0],
        slip_adaptation: 0.8,
        rolling_friction: 0.2,
        spinning_friction: 0.7,
        restitution: 0.6,
        block_damage_factor: 0.05,
        impact_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
        ],
        damage_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'entity_type', id: 'minecraft:slime' } },
            { operation: 'multiply', value: 0.1, condition: { type: 'entity_type', id: 'minecraft:magma_cube' } },
        ],
    },
    'machine_max:racing_tire': {
        friction: [3.0, 3.0, 1.0],
        slip_adaptation: 0.3,
        slip_curve: { longitudinal: { peak_slip_ratio: 0.20, peak_scale: 1.4, kinetic_scale: 0.9 }, lateral: { peak_angle_deg: 25.0, peak_scale: 1.4, kinetic_scale: 0.9 } },
        rolling_friction: 0.015,
        spinning_friction: 1.3,
        restitution: 0.4,
        block_damage_factor: 0.05,
        impact_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
        ],
        damage_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'entity_type', id: 'minecraft:slime' } },
            { operation: 'multiply', value: 0.1, condition: { type: 'entity_type', id: 'minecraft:magma_cube' } },
        ],
    },
    'machine_max:drifting_tire': {
        friction: [1.4, 1.5, 1.0],
        slip_adaptation: 0.4,
        slip_curve: { longitudinal: { peak_slip_ratio: 0.16, peak_scale: 1.2, kinetic_scale: 0.6 }, lateral: { peak_angle_deg: 7.0, kinetic_angle_deg: 90.0, peak_scale: 1.3, kinetic_scale: 0.1 } },
        rolling_friction: 0.01,
        spinning_friction: 0.8,
        restitution: 0.65,
        block_damage_factor: 0.05,
        impact_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
        ],
        damage_modifiers: [
            { operation: 'multiply', value: 0.1, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'add', value: -2.0, condition: { type: 'damage_tag', id: 'c:is_impact' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.05, condition: { type: 'entity_type', id: 'minecraft:slime' } },
            { operation: 'multiply', value: 0.1, condition: { type: 'entity_type', id: 'minecraft:magma_cube' } },
        ],
    },
    'machine_max:pvc': {
        friction: [0.55, 0.55, 0.5],
        slip_adaptation: 0.38,
        rolling_friction: 0.018,
        spinning_friction: 0.38,
        restitution: 0.55,
        block_damage_factor: 0.7,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -4.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:paper': {
        friction: [0.55, 0.55, 0.5],
        slip_adaptation: 0.9,
        rolling_friction: 0.05,
        spinning_friction: 0.3,
        restitution: 0.01,
        block_damage_factor: 0.7,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -4.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
    'machine_max:ice': {
        friction: [0.15, 0.15, 0.5],
        slip_adaptation: 0.05,
        rolling_friction: 0.001,
        spinning_friction: 0.05,
        restitution: 0.05,
        block_damage_factor: 0.7,
        angle_effect: true,
        impact_modifiers: [
            { operation: 'multiply', value: 0.85, condition: { type: 'always' } },
        ],
        damage_modifiers: [
            { operation: 'add', value: -4.0, condition: { type: 'damage_type', id: 'minecraft:fly_into_wall' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'damage_type', id: 'minecraft:sweet_berry_bush' } },
            { operation: 'multiply', value: 0.04, condition: { type: 'entity_type', id: 'minecraft:slime' } },
        ],
        un_penetrate_damage_factor: 0.0,
        sounds: { hit_un_pen: { sound_id: 'machine_max:hit_box.hit.up_pen.metal', range: 64 }, hit_pen: { sound_id: 'machine_max:hit_box.hit.pen.metal', range: 64 } },
    },
};

const PROJECTILE_DEFAULTS = {
    type: 'point',
    mass: 1.0,
    gravity_factor: 1.0,
    drag_factor: 0,
    radius: 0.05,
    base_velocity: 100.0,
    base_penetration: 10.0,
    base_damage: 10.0,
    base_accuracy_mil: 5.0,
    penetration_velocity_coefficient: 1.0,
    damage_velocity_coefficient: 1.0,
};

if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        CONFIG_VERSION,
        PART_DEFAULTS,
        VARIANT_DEFAULTS,
        SUB_PART_DEFAULTS,
        CONNECTOR_DEF_DEFAULTS,
        SUBSYSTEM_DEF_DEFAULTS,
        HIT_BOX_DEFAULTS,
        MATERIAL_DEF_DEFAULTS,
        PRESET_MATERIAL_DEFS,
        PROJECTILE_DEFAULTS,
    };
}
